name: Get Name

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
    # The branches below must be a subset of the branches above
#    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Gett Name
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Get Name
        run: hostname
